In [3]:
import pandas as pd

df = pd.read_csv("./failure_prediction.csv")

print(df)

     Id                  Time              Machine Component  \
0    48  2022-06-03T08:09:29Z          Excavator_1    Engine
1     5  2022-05-12T02:05:42Z  Articulated_Truck_1      Fuel
2    24  2022-05-27T06:25:04Z  Articulated_Truck_1    Engine
3    23  2022-05-12T20:36:47Z     Backhoe_Loader_1     Drive
4    42  2022-06-28T04:06:30Z          Excavator_1    Engine
..   ..                   ...                  ...       ...
995  18  2022-06-29T16:29:54Z      Asphalt_Paver_1      Misc
996  43  2022-06-29T16:52:23Z      Asphalt_Paver_1      Fuel
997  28  2022-06-29T20:00:46Z      Asphalt_Paver_1      Misc
998   4  2022-06-30T14:09:21Z      Asphalt_Paver_1      Misc
999  14  2022-06-30T14:47:40Z      Asphalt_Paver_1      Misc

                   Parameter  Value
0                Temparature  104.0
1              Water in Fuel   70.0
2                Temparature  104.0
3      Transmission Pressure  231.0
4               Oil Pressure   39.0
..                       ...    ...
995  Exhaust Gas Temparature  263.0
996                    Level    7.0
997      Air Filter Pressure   23.0
998      Air Filter Pressure   26.0
999  Exhaust Gas Temparature  195.0

[1000 rows x 6 columns]

In [4]:
print(df['Parameter'])

0                  Temparature
1                Water in Fuel
2                  Temparature
3        Transmission Pressure
4                 Oil Pressure
                ...
995    Exhaust Gas Temparature
996                      Level
997        Air Filter Pressure
998        Air Filter Pressure
999    Exhaust Gas Temparature
Name: Parameter, Length: 1000, dtype: object

In [5]:
type(df['Parameter'])

pandas.core.series.Series

In [10]:
for i, elem in enumerate(df['Parameter']):
    if "Temparature" in elem:
        # df['Parameter'][i] = df['Parameter'][i].replace('Temparature', 'Temperature')
        df.loc[i, 'Parameter'] = df['Parameter'][i].replace('Temparature', 'Temperature')

In [14]:
df

,Id,Time,Machine,Component,Parameter,Value
0,48,2022-06-03T08:09:29Z,Excavator_1,Engine,Temperature,104.0
1,5,2022-05-12T02:05:42Z,Articulated_Truck_1,Fuel,Water in Fuel,70.0
2,24,2022-05-27T06:25:04Z,Articulated_Truck_1,Engine,Temperature,104.0
3,23,2022-05-12T20:36:47Z,Backhoe_Loader_1,Drive,Transmission Pressure,231.0
4,42,2022-06-28T04:06:30Z,Excavator_1,Engine,Oil Pressure,39.0
...,...,...,...,...,...,...
995,18,2022-06-29T16:29:54Z,Asphalt_Paver_1,Misc,Exhaust Gas Temperature,263.0
996,43,2022-06-29T16:52:23Z,Asphalt_Paver_1,Fuel,Level,7.0
997,28,2022-06-29T20:00:46Z,Asphalt_Paver_1,Misc,Air Filter Pressure,23.0
998,4,2022-06-30T14:09:21Z,Asphalt_Paver_1,Misc,Air Filter Pressure,26.0
999,14,2022-06-30T14:47:40Z,Asphalt_Paver_1,Misc,Exhaust Gas Temperature,195.0

In [28]:
df.to_csv('failure_predictions_1.csv', index=False)

In [24]:
df

,Id,Time,Machine,Component,Parameter,Value,Risk
0,48,2022-06-03T08:09:29Z,Excavator_1,Engine,Temperature,104.0,No
1,5,2022-05-12T02:05:42Z,Articulated_Truck_1,Fuel,Water in Fuel,70.0,No
2,24,2022-05-27T06:25:04Z,Articulated_Truck_1,Engine,Temperature,104.0,No
3,23,2022-05-12T20:36:47Z,Backhoe_Loader_1,Drive,Transmission Pressure,231.0,No
4,42,2022-06-28T04:06:30Z,Excavator_1,Engine,Oil Pressure,39.0,No
...,...,...,...,...,...,...,...
995,18,2022-06-29T16:29:54Z,Asphalt_Paver_1,Misc,Exhaust Gas Temperature,263.0,No
996,43,2022-06-29T16:52:23Z,Asphalt_Paver_1,Fuel,Level,7.0,No
997,28,2022-06-29T20:00:46Z,Asphalt_Paver_1,Misc,Air Filter Pressure,23.0,No
998,4,2022-06-30T14:09:21Z,Asphalt_Paver_1,Misc,Air Filter Pressure,26.0,No
999,14,2022-06-30T14:47:40Z,Asphalt_Paver_1,Misc,Exhaust Gas Temperature,195.0,No

In [25]:
df = pd.read_csv("./failure_predictions_1_copy.csv")

def calculate_risk(row):
    # Engine Temperature
    if row['Component'] == "Engine" and row['Parameter'] == "Temperature":
        if row['Value'] < 105:
            return "No"
        else:
            return "Yes"
        
    # Engine Oil Pressure
    elif row['Component'] == "Engine" and row['Parameter'] == "Oil Pressure":
        if 25 < row['Value'] < 65:
            return "No"
        else:
            return "Yes"
        
    # Engine Speed
    elif row['Component'] == "Engine" and row['Parameter'] == "Speed":
        if row['Value'] < 1800:
            return "No"
        else:
            return "Yes"
        
    # Drive, Brake Control
    elif row['Component'] == "Drive" and row['Parameter'] == "Brake Control":
        if row['Value'] > 1:
            return "No"
        else:
            return "Yes"
        
    # Drive, Transmission Pressure
    elif row['Component'] == "Drive" and row['Parameter'] == "Transmission Pressure":
        if 200 < row['Value'] < 450:
            return "No"
        else:
            return "Yes"
    
    # Drive, Pedal Sensor
    elif row['Component'] == "Drive" and row['Parameter'] == "Pedal Sensor":
        if row['Value'] < 4.7:
            return "No"
        else:
            return "Yes"
    
    # Fuel, Water in Fuel
    elif row['Component'] == "Fuel" and row['Parameter'] == "Water in Fuel":
        if row['Value'] < 1800:
            return "No"
        else:
            return "Yes"
    
    # Fuel, Level
    elif row['Component'] == "Fuel" and row['Parameter'] == "Level":
        if row['Value'] > 1:
            return "No"
        else:
            return "Yes"
        
    # Fuel, Pressure
    elif row['Component'] == "Fuel" and row['Parameter'] == "Pressure":
        if 35 < row['Value'] < 65:
            return "No"
        else:
            return "Yes"
        
    # Fuel, Temperature
    elif row['Component'] == "Fuel" and row['Parameter'] == "Temperature":
        if row['Value'] < 400:
            return "No"
        else:
            return "Yes"
        
    # Misc, System Voltage
    elif row['Component'] == "Misc" and row['Parameter'] == "System Voltage":
        if 12 < row['Value'] < 15:
            return "No"
        else:
            return "Yes"
        
    # Misc, Exhaust Gas Temperature
    elif row['Component'] == "Misc" and row['Parameter'] == "Exhaust Gas Temperature":
        if row['Value'] < 365:
            return "No"
        else:
            return "Yes"
        
    # Misc, Hydraulic Pump Rate
    elif row['Component'] == "Misc" and row['Parameter'] == "Hydraulic Pump Rate":
        if row['Value'] < 125:
            return "No"
        else:
            return "Yes"
        
    # Misc, Air Filter Pressure
    elif row['Component'] == "Misc" and row['Parameter'] == "Air Filter Pressure":
        if row['Value'] > 20:
            return "No"
        else:
            return "Yes"
    # Fits into none of the categories   
    else:
        return -1   
    

df['Risk'] = df.apply(calculate_risk, axis=1)

In [26]:
df

,Id,Time,Machine,Component,Parameter,Value,Risk
0,48,2022-06-03T08:09:29Z,Excavator_1,Engine,Temperature,104.0,No
1,5,2022-05-12T02:05:42Z,Articulated_Truck_1,Fuel,Water in Fuel,70.0,No
2,24,2022-05-27T06:25:04Z,Articulated_Truck_1,Engine,Temperature,104.0,No
3,23,2022-05-12T20:36:47Z,Backhoe_Loader_1,Drive,Transmission Pressure,231.0,No
4,42,2022-06-28T04:06:30Z,Excavator_1,Engine,Oil Pressure,39.0,No
...,...,...,...,...,...,...,...
995,18,2022-06-29T16:29:54Z,Asphalt_Paver_1,Misc,Exhaust Gas Temperature,263.0,No
996,43,2022-06-29T16:52:23Z,Asphalt_Paver_1,Fuel,Level,7.0,No
997,28,2022-06-29T20:00:46Z,Asphalt_Paver_1,Misc,Air Filter Pressure,23.0,No
998,4,2022-06-30T14:09:21Z,Asphalt_Paver_1,Misc,Air Filter Pressure,26.0,No
999,14,2022-06-30T14:47:40Z,Asphalt_Paver_1,Misc,Exhaust Gas Temperature,195.0,No

In [27]:
count_1 = 0
count_0 = 0
count_11 = 0
for elem in df['Risk']:
    if elem == 1:
        count_1 += 1
    elif elem == -1:
        count_11 += 1
    else:
        count_0 += 1
        
print(f"count1: {count_1}, count0: {count_0}, count11: {count_11}")

count1: 0, count0: 1000, count11: 0

In [30]:
df = pd.read_csv("./failure_predictions_1.csv")

for elem in df:
    print(elem)
    # if elem["Id"] == 5:
    #     print(elem)

Id
Time
Machine
Component
Parameter
Value
Risk

In [31]:
df = pd.read_csv("./failure_predictions_1_copy_2.csv")
df

,Id,Time,Machine,Component,Parameter,Value,Risk
0,48,2022-06-03T08:09:29Z,Excavator_1,Engine,Temperature,104.0,No
1,5,2022-05-12T02:05:42Z,Articulated_Truck_1,Fuel,Water in Fuel,70.0,No
2,24,2022-05-27T06:25:04Z,Articulated_Truck_1,Engine,Temperature,104.0,No
3,23,2022-05-12T20:36:47Z,Backhoe_Loader_1,Drive,Transmission Pressure,231.0,No
4,42,2022-06-28T04:06:30Z,Excavator_1,Engine,Oil Pressure,39.0,No
...,...,...,...,...,...,...,...
995,18,2022-06-29T16:29:54Z,Asphalt_Paver_1,Misc,Exhaust Gas Temperature,263.0,No
996,43,2022-06-29T16:52:23Z,Asphalt_Paver_1,Fuel,Level,7.0,No
997,28,2022-06-29T20:00:46Z,Asphalt_Paver_1,Misc,Air Filter Pressure,23.0,No
998,4,2022-06-30T14:09:21Z,Asphalt_Paver_1,Misc,Air Filter Pressure,26.0,No
999,14,2022-06-30T14:47:40Z,Asphalt_Paver_1,Misc,Exhaust Gas Temperature,195.0,No

In [33]:
def get_normal_time(iso_time):
    from datetime import datetime
    datetime_obj = datetime.strptime(iso_time, "%Y-%m-%dT%H:%M:%SZ")
    human_readable = datetime_obj.strftime("%B %d, %Y %I:%M:%S %p UTC")
    return human_readable

In [34]:
for i, elem in enumerate(df['Time']):
    df.loc[i, 'Time'] = get_normal_time(elem)

In [35]:
df

,Id,Time,Machine,Component,Parameter,Value,Risk
0,48,"June 03, 2022 08:09:29 AM UTC",Excavator_1,Engine,Temperature,104.0,No
1,5,"May 12, 2022 02:05:42 AM UTC",Articulated_Truck_1,Fuel,Water in Fuel,70.0,No
2,24,"May 27, 2022 06:25:04 AM UTC",Articulated_Truck_1,Engine,Temperature,104.0,No
3,23,"May 12, 2022 08:36:47 PM UTC",Backhoe_Loader_1,Drive,Transmission Pressure,231.0,No
4,42,"June 28, 2022 04:06:30 AM UTC",Excavator_1,Engine,Oil Pressure,39.0,No
...,...,...,...,...,...,...,...
995,18,"June 29, 2022 04:29:54 PM UTC",Asphalt_Paver_1,Misc,Exhaust Gas Temperature,263.0,No
996,43,"June 29, 2022 04:52:23 PM UTC",Asphalt_Paver_1,Fuel,Level,7.0,No
997,28,"June 29, 2022 08:00:46 PM UTC",Asphalt_Paver_1,Misc,Air Filter Pressure,23.0,No
998,4,"June 30, 2022 02:09:21 PM UTC",Asphalt_Paver_1,Misc,Air Filter Pressure,26.0,No
999,14,"June 30, 2022 02:47:40 PM UTC",Asphalt_Paver_1,Misc,Exhaust Gas Temperature,195.0,No